# Generated by Django 4.2.7 on 2026-01-17 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('sign_language', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_signs_learned', models.IntegerField(default=0)),
                ('total_videos_watched', models.IntegerField(default=0)),
                ('total_lessons_completed', models.IntegerField(default=0)),
                ('total_practice_time', models.IntegerField(default=0, help_text='Total practice time in seconds')),
                ('current_streak', models.IntegerField(default=0, help_text='Days of consecutive learning')),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Learning Stats',
            },
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_watched', models.BooleanField(default=False)),
                ('watch_count', models.IntegerField(default=0)),
                ('last_watched_at', models.DateTimeField(blank=True, null=True)),
                ('watch_duration', models.IntegerField(default=0, help_text='Total seconds watched')),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='sign_language.video')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'is_completed'], name='progress_vi_user_id_fdc563_idx')],
                'unique_together': {('user', 'video')},
            },
        ),
        migrations.CreateModel(
            name='SignProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_learned', models.BooleanField(default=False)),
                ('practice_count', models.IntegerField(default=0)),
                ('last_practiced_at', models.DateTimeField(blank=True, null=True)),
                ('mastery_score', models.FloatField(default=0.0, help_text='Score from 0.0 to 100.0')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='sign_language.sign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sign_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'is_learned'], name='progress_si_user_id_51ac6b_idx'), models.Index(fields=['sign', 'mastery_score'], name='progress_si_sign_id_fcd0c6_idx')],
                'unique_together': {('user', 'sign')},
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('watch_count', models.IntegerField(default=0)),
                ('last_watched_at', models.DateTimeField(blank=True, null=True)),
                ('watch_duration', models.IntegerField(default=0, help_text='Total seconds watched')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['lesson__order'],
                'indexes': [models.Index(fields=['user', 'is_completed'], name='progress_le_user_id_734ee4_idx')],
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
