# Generated by Django 4.2.7 on 2026-01-17 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sign_language', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('language', models.CharField(choices=[('ASL', 'American Sign Language'), ('ISL', 'Indian Sign Language'), ('BSL', 'British Sign Language')], max_length=3)),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/')),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('duration_hours', models.FloatField(default=0.0, help_text='Estimated course duration in hours')),
                ('enrolled_count', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0, help_text='Average rating out of 5')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructed_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-is_featured'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video', models.FileField(upload_to='courses/lessons/videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/lessons/thumbnails/')),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('order', models.IntegerField(default=0, help_text='Order of lesson in the course')),
                ('is_free', models.BooleanField(default=False, help_text='Can be accessed without enrollment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
                ('signs', models.ManyToManyField(blank=True, help_text='Signs covered in this lesson', related_name='lessons', to='sign_language.sign')),
            ],
            options={
                'ordering': ['course', 'order', 'created_at'],
                'indexes': [models.Index(fields=['course', 'order'], name='courses_les_course__dc0bc6_idx')],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enrolled_at'],
                'indexes': [models.Index(fields=['user', 'is_completed'], name='courses_enr_user_id_c7702f_idx')],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['language', 'difficulty_level'], name='courses_cou_languag_953d33_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_published', 'is_featured'], name='courses_cou_is_publ_bc1413_idx'),
        ),
    ]
