# Generated by Django 4.2.7 on 2026-01-17 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('language', models.CharField(choices=[('ASL', 'American Sign Language'), ('ISL', 'Indian Sign Language'), ('BSL', 'British Sign Language')], max_length=3)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='signs/images/')),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signs', to='sign_language.category')),
            ],
            options={
                'ordering': ['word', 'language'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_file', models.FileField(upload_to='signs/videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='signs/thumbnails/')),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('description', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_videos', to=settings.AUTH_USER_MODEL)),
                ('sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='sign_language.sign')),
            ],
            options={
                'ordering': ['-created_at', '-is_featured'],
                'indexes': [models.Index(fields=['sign', 'is_featured'], name='sign_langua_sign_id_6134e1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sign',
            index=models.Index(fields=['language', 'category'], name='sign_langua_languag_e86f15_idx'),
        ),
        migrations.AddIndex(
            model_name='sign',
            index=models.Index(fields=['difficulty_level'], name='sign_langua_difficu_e6257c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sign',
            unique_together={('word', 'language')},
        ),
    ]
